version: '3.8'

services:
  app:
    image: dziennik-szkolny:latest
    container_name: moj-dziennik
    ports:
      - "8080:8080"
    volumes:
      # To magiczna linijka. Łączy Twój folder db_data z folderem w kontenerze.
      - ./db_data:/app/db_data